# This is a basic workflow to help you get started with Actions

name: Run Unit Tests

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: dotnet rest --no-build --verbosity normal
